# Generated by Django 4.2.4 on 2023-11-04 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_forums', '0006_alter_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
